apiVersion: v1
kind: ConfigMap
metadata:
  name: balance-calculator-config
  labels:
    app: balance-calculator
data:
  # Database Configuration
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "balance_calculator"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DATABASE: "0"
  REDIS_TIMEOUT: "10000"
  REDIS_MAX_ACTIVE: "8"
  REDIS_MAX_WAIT: "-1"
  REDIS_MAX_IDLE: "8"
  REDIS_MIN_IDLE: "0"
  
  # Application Configuration
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_APP: "INFO" 