apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: balance-calculator
  template:
    metadata:
      labels:
        app: balance-calculator
    spec:
      containers:
      - name: balance-calculator
        image: balance-calculator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: logs-volume
          mountPath: /app/logs
        env:
        - name: K8S_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: balance-calculator-secret
              key: datasource-username
        - name: K8S_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: balance-calculator-secret
              key: datasource-password
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "balance_calculator"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: balance-calculator-secret
              key: redis-password
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
      volumes:
      - name: config-volume
        configMap:
          name: balance-calculator-config
      - name: logs-volume
        emptyDir: {} 