apiVersion: apps/v1
kind: Deployment
metadata:
  name: balance-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: balance-calculator
  template:
    metadata:
      labels:
        app: balance-calculator
    spec:
      containers:
      - name: balance-calculator
        image: crpi-5zsy79qqob1c1hsk.cn-hangzhou.personal.cr.aliyuncs.com/flynn_11122/balance-calculator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: logs-volume
          mountPath: /app/logs
        env:
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: balance-calculator-secret
              key: DATASOURCE_USERNAME
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: balance-calculator-secret
              key: DATASOURCE_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: balance-calculator-secret
              key: REDIS_PASSWORD
        envFrom:
        - configMapRef:
            name: balance-calculator-config
      volumes:
      - name: config-volume
        configMap:
          name: balance-calculator-config
      - name: logs-volume
        emptyDir: {} 