apiVersion: v1
kind: Service
metadata:
  name: balance-calculator
spec:
  type: LoadBalancer
  selector:
    app: balance-calculator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 