spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hsbchomework
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# Kubernetes Secret配置
kubernetes:
  secrets:
    datasource:
      username: ${K8S_DATASOURCE_USERNAME}
      password: ${K8S_DATASOURCE_PASSWORD}

server:
  port: 8080

logging:
  level:
    com.fly.hsbchomework: ERROR
    org.springframework: ERROR